# Generated by Django 2.2.4 on 2023-09-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='荣誉描述')),
                ('photo', models.ImageField(blank=True, upload_to='Award/', verbose_name='荣誉照片')),
            ],
        ),
    ]
