# Generated by Django 2.2.4 on 2023-09-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': '获奖和荣誉', 'verbose_name_plural': '获奖和荣誉'},
        ),
    ]
